import { Project, FilterOption } from './portfolio-types';

export const projectTypeFilters: FilterOption[] = [
  { value: 'all', label: 'All Projects' },
  { value: 'website', label: 'Websites' },
  { value: 'mobile', label: 'Mobile Apps' },
];

export const categoryFilters: FilterOption[] = [
  { value: 'all', label: 'All Categories' },
  { value: 'ecommerce', label: 'E-commerce' },
  { value: 'business', label: 'Business & Corporate' },
  { value: 'media', label: 'Media & Entertainment' },
  { value: 'realestate', label: 'Real Estate' },
  { value: 'education', label: 'Education' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'sports', label: 'Sports & Fitness' },
];

export const projects: Project[] = [
  {
    id: 1,
    title: 'SDLPKB',
    description: 'Bathrooms, Kitchens, Painting & Decorating Experts',
    type: 'website',
    category: 'business',
    image: '/lovable-uploads/0bcc5122-64f0-4d53-bd52-e65ad96598c9.png',
    url: 'https://sdlpkb.co.uk',
    technologies: [],
  },
  {
    id: 2,
    title: 'We Care',
    description: 'Property Maintenance and Renovation Specialists',
    type: 'website',
    category: 'business',
    image: '/lovable-uploads/bef70640-914a-4488-b5e4-11fb224be0d4.png',
    technologies: [],
  },
  {
    id: 3,
    title: 'AgentGenesis',
    description: 'Create & Deploy AI Agents for Your Business - Design, customize, and deploy AI agents for sales, support, marketing, and more with no coding required',
    type: 'website',
    category: 'business',
    image: '/lovable-uploads/c776d86e-8d7b-401e-a57a-8b2e92ded1b0.png',
    technologies: [],
  },
  {
    id: 4,
    title: 'PocketRx',
    description: 'Your Pharmacy in Your Pocket - Fast, secure, and convenient access to prescriptions and over-the-counter medications delivered right to your doorstep',
    type: 'website',
    category: 'healthcare',
    image: '/lovable-uploads/f03e6649-06cb-48ad-9a43-c1470f147991.png',
    technologies: [],
  },
  {
    id: 5,
    title: 'DAMAC Academy',
    description: 'Professional football training programs for all ages in Damac Hills 2, Dubai. Learn from experienced coaches and take your game to the next level.',
    type: 'website',
    category: 'sports',
    image: '/lovable-uploads/3f7c100f-ba5d-46bf-bd28-d8dff9a07bce.png',
    technologies: [],
  },
  {
    id: 6,
    title: 'Future Village',
    description: 'Learning Management System for tech education and career development',
    type: 'website',
    category: 'education',
    image: '/lovable-uploads/04920204-a50e-4d5c-86bb-db3f605cd8cb.png',
    technologies: [],
  },
  {
    id: 7,
    title: 'Melody Tribe',
    description: 'Music streaming platform for discovering African beats and trending tracks',
    type: 'website',
    category: 'media',
    image: '/lovable-uploads/4140db43-1bf6-4494-9568-9aed7ebcf16d.png',
    technologies: [],
  },
  {
    id: 8,
    title: 'Africas Estate',
    description: 'Your Trusted Real Estate Marketplace in Africa - connecting verified buyers, sellers, and service providers',
    type: 'website',
    category: 'realestate',
    image: '/lovable-uploads/fb9dc802-a6df-4e9d-8526-46abd52d5d37.png',
    technologies: [],
  },
  {
    id: 9,
    title: 'E-commerce Platform',
    description: 'Full-featured online store with payment integration and inventory management.',
    type: 'website',
    category: 'ecommerce',
    image: '/placeholder.svg',
    technologies: [],
  },
  {
    id: 10,
    title: 'Property Management App',
    description: 'Mobile application for real estate agents to manage properties and client relationships.',
    type: 'mobile',
    category: 'realestate',
    image: '/placeholder.svg',
    technologies: [],
  },
  {
    id: 11,
    title: 'Learning Management System',
    description: 'Educational platform with course management and student progress tracking.',
    type: 'website',
    category: 'education',
    image: '/placeholder.svg',
    technologies: [],
  },
  {
    id: 12,
    title: 'Streaming Platform',
    description: 'Video streaming application with content management and user subscriptions.',
    type: 'website',
    category: 'media',
    image: '/placeholder.svg',
    technologies: [],
  },
  {
    id: 13,
    title: 'Restaurant Ordering App',
    description: 'Mobile app for food ordering with real-time tracking and payment processing.',
    type: 'mobile',
    category: 'ecommerce',
    image: '/placeholder.svg',
    technologies: [],
  },
];
